import Header from './Header';
import Footer from './Footer';
import Head from 'next/head';

const index = (props) => {
    return (
        <div>
            <Head>
                <title>studyoda</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js" async />
                <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js" async />
            </Head>
            <Header />
            {props.children}
            <Footer />
        </div>
    );
};

export default index;
