import Header from './Header';
import Footer from './Footer';
import Head from 'next/head';
import Navbar from '../Home/Navbar/Navbar';
import CopyRight from './CopyRight';

const index = (props) => {
    return (
        <div>
            <Head>
                <title>studyoda</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer />
                <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js" async />
                <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js" async />
                <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js" />
                <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js" />
            </Head>
            {/* <Navbar /> */}
            <Header />
            {props.children}
            <Footer />
            <CopyRight />
        </div>
    );
};

export default index;
